### PR TITLE
Update graph implementation and add dropdown county selection

### LINKED ISSUE #22: Update chart with dropdown menu
The current chart implementation has a dropdown menu that is hidden. the @material/mwc-select component being used does not currently allow for passing sizing information to the mwc-menu used internally. This is causing the menu to not display when the height of the container extends past the view height of the screen.

An alternative dropdown component needs to be implemented or the current needs to be fixed.

In the mean time, the chart is set to show all counties in addition to the total count in SC.

### LINKED ISSUE #23: Update chart with visual enhancements
The chart needs additional visual enhancements implemented. (this is Dev, not design)
Several items are intentionally missing at the moment, such as:
- [x] Data tooltip on click or hover over data points
 - [ ] Additional legend entry for selected county
 - [x] Height limitations to the container for better desktop support
 - [x] Abbreviated date labels on x-axes, and maybe an increase in interval between ticks.
 - [ ] Any color/background/line styling enhancements to match mockups

### LINKED ISSUE #62: [Homepage]: Add graph
# Feature request

## Feature type (Frontend / Backend / Other)
frontend/backend

## Desired Functionality
Add graph that shows the number of cases per county over time. 
We can show the number of cases in SC over time as a constant, and be able to select which SC county to compare that with. 

We should _only_ show South Carolina counties here to keep the data focused and easily digestible.

https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e8222bb78c56a1630d2f56c/
Homepage

https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e8222bf120af47227babcc9/
Homepage

### Dropdown menu
Dropdown menu height = 288px
Min-width = 288px
Max-width = 392px
https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e94b5cd9be6bd79c045ddca/
Dropdown
https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e94b5d0dfa2157a54375056/
Dropdown

## Other remarks
Design issue: https://github.com/CovidSC/covidsc-web/issues/16

### PR DESCRIPTION
**Pull request by colbyhill21**
## Request Description / Summary
Updates `mwc-select` implementation to allow county selection, defaulting to the first item in the list.
CovidSCDropdown3

Updates `chartjs` implementation to show tooltips, use `M/d` date display, show legend, and display the selected county and state data. (also includes built-in legend functionality to show/hide data)
CovidSCGraph

## Tag the local or remote issues that are related
 closes #22 
 closes #23 
 closes #62

### CODE REVIEW

**Comment by krumware** [comment]
@ncraley can you by chance check out the docs folder from master and push to resolve those conflicted files? those shouldn't have been committed by colby

**Comment by ncraley** [comment]
@krumware Cleared out docs on this branch and checked out the version from master. Still showing in changed files, though? Not sure why, looks like it's showing renames/moves, but the "new" files have the same names as the ones on master.

**Comment by ncraley** [comment]
@krumware Fixed dropdown styling issue, looks good on https://viz-enhancements.covid-sc.dev.krum.io/

**Comment by ncraley** [comment]
@krumware Added Top 3 default for the dropdown/graph:

image

image

**Comment by krumware** [comment]
I'll go ahead and update the docs folder

**Pull request merged**
